export const USER_REGISTER = 'RABADAN/USER/REGISTER';
export const USER_REGISTER_SUCCESS = 'RABADAN/USER/REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'RABADAN/USER/REGISTER_FAIL';

export const USER_LOGIN = 'RABADAN/USER/LOGIN';
export const USER_LOGIN_SUCCESS = 'RABADAN/USER/LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'RABADAN/USER/LOGIN_FAIL';

export const SET_USER = 'RABADAN/USER/SET_USER';

export const USER_LOGOUT = 'RABADAN/USER/LOGOUT';

export const SET_MESSAGE = 'RABADAN/MESSAGE/SET';
export const CLEAR_MESSAGE = 'RABADAN/MESSAGE/CLEAR';

export const GET_BLOGS = 'RABADAN/BLOG/INDEX';
export const GET_BLOGS_SUCCESS = 'RABADAN/BLOG/INDEX_SUCCESS';
export const GET_BLOGS_FAIL = 'RABADAN/BLOG/INDEX_FAIL';
export const GET_BLOG = 'RABADAN/BLOG/SHOW';
export const GET_BLOG_SUCCESS = 'RABADAN/BLOG/SHOW_SUCCESS';
export const GET_BLOG_FAIL = 'RABADAN/BLOG/SHOW_FAIL';
export const SET_BLOG = 'RABADAN/BLOG/SET';
export const SET_BLOG_SUCCESS = 'RABADAN/BLOG/SET_SUCCESS';
export const SET_BLOG_FAIL = 'RABADAN/BLOG/SET_FAIL';
export const CHANGE_BLOG = 'RABADAN/BLOG/CHANGE_BLOG';