export const USER_REGISTER = 'RABADAN/USER/REGISTER';
export const USER_REGISTER_SUCCESS = 'RABADAN/USER/REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'RABADAN/USER/REGISTER_FAIL';
export const USER_LOGIN = 'RABADAN/USER/LOGIN';
export const USER_LOGIN_SUCCESS = 'RABADAN/USER/LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'RABADAN/USER/LOGIN_FAIL';
export const USER_LOGOUT = 'RABADAN/USER/LOGOUT';

export const SET_MESSAGE = 'RABADAN/MESSAGE/SET';
export const CLEAR_MESSAGE = 'RABADAN/MESSAGE/CLEAR';
